import type {
  MemberBenefitMatrixRow,
  MemberCenterDocument,
  MemberFaqItem,
  MemberPlan,
  MemberPlanId,
} from "@/features/tools/member/types/member"

const memberPlanRows: MemberPlan[] = [
  {
    id: "free",
    title: "免费会员",
    priceCoins: 0,
    durationLabel: "永久",
    intro: "注册后默认获得，适合轻度使用功能的用户。",
    features: [
      "文件收集 免费使用",
      "ER图生成 按次付费",
      "AIGC检测 仅一次免费",
      "各AI功能 免费体验一次",
      "其余能力按次计费使用",
    ],
    buttonLabel: "免费使用",
    disabled: true,
    current: true,
    accentClassName: "from-slate-300 via-slate-300 to-slate-200",
    buttonClassName:
      "border-slate-300 bg-slate-100 text-slate-500 cursor-not-allowed",
    textAccentClassName: "text-slate-600",
  },
  {
    id: "week",
    title: "周会员",
    badge: "轻量冲刺",
    subBadge: "适合阶段作业",
    priceCoins: 1180,
    durationLabel: "7天",
    originalPriceCoins: 1480,
    saveYuan: 2.5,
    intro: "适合短期课程冲刺与集中提交阶段。",
    features: [
      "SQL转ER图 无限次",
      "AI生成ER图 20次/天",
      "AIGC检测/降AIGC率 各10次/天",
      "论文降重 8次/天",
      "各AI工具 15次/天起",
      "代码生成享 9.2折",
    ],
    buttonLabel: "立即开通",
    promoLabel: "短期高频",
    accentClassName: "from-sky-500 via-cyan-500 to-blue-500",
    buttonClassName: "bg-sky-500 text-white hover:bg-sky-600",
    textAccentClassName: "text-sky-600",
  },
  {
    id: "month",
    title: "月会员",
    badge: "主流选择",
    subBadge: "30天稳定产出",
    promoLabel: "推荐方案",
    priceCoins: 3980,
    durationLabel: "30天",
    originalPriceCoins: 4980,
    saveYuan: 8.3,
    intro: "覆盖课程全周期，额度与客服响应更均衡。",
    features: [
      "SQL转ER图 无限次",
      "AI生成ER图 45次/天",
      "AIGC检测/降AIGC率 各28次/天",
      "论文降重 40次/天",
      "各AI工具 40-60次/天",
      "7×16在线客服 + 优先处理",
      "代码生成享 8.6折",
    ],
    buttonLabel: "立即开通",
    accentClassName: "from-violet-500 via-purple-500 to-fuchsia-500",
    buttonClassName: "bg-violet-500 text-white hover:bg-violet-600",
    textAccentClassName: "text-violet-600",
  },
  {
    id: "year",
    title: "年会员",
    badge: "长期研发",
    subBadge: "性价比最高",
    priceCoins: 26800,
    durationLabel: "365天",
    originalPriceCoins: 32800,
    saveYuan: 50,
    intro: "适合长期项目与论文密集阶段，额度充足。",
    features: [
      "SQL转ER图 无限次",
      "AI生成ER图 120次/天",
      "AIGC检测/降AIGC率 各80次/天",
      "论文降重 220次/天",
      "各AI工具 120-180次/天",
      "专属客服 + 新功能优先体验",
      "代码生成享 7.5折",
    ],
    buttonLabel: "立即开通",
    accentClassName: "from-amber-500 via-orange-500 to-orange-600",
    buttonClassName: "bg-orange-500 text-white hover:bg-orange-600",
    textAccentClassName: "text-orange-600",
  },
]

const memberMatrixRows: MemberBenefitMatrixRow[] = [
  {
    id: "er-sql",
    category: "ER图工具",
    feature: "SQL转ER图",
    free: "(节点*3)金币/次",
    week: "无限次",
    month: "无限次",
    year: "无限次",
  },
  {
    id: "er-ai",
    feature: "AI生成ER图",
    free: "(40+字数*4)金币/次",
    week: "20次/天",
    month: "45次/天",
    year: "120次/天",
  },
  {
    id: "paper-detect",
    category: "论文工具",
    feature: "AIGC检测",
    free: "(40/千字)金币/次(赠1次体验)",
    week: "10次/天",
    month: "28次/天",
    year: "80次/天",
  },
  {
    id: "paper-reduce",
    feature: "降AIGC率",
    free: "(80/千字)金币/次(赠1次体验)",
    week: "10次/天",
    month: "28次/天",
    year: "80次/天",
  },
  {
    id: "paper-rewrite",
    feature: "论文降重",
    free: "(160/千字)金币/次",
    week: "8次/天",
    month: "40次/天",
    year: "220次/天",
  },
  {
    id: "ai-structure",
    category: "AI生成工具",
    feature: "AI生成功能结构图",
    free: "16金币/次",
    week: "15次/天",
    month: "40次/天",
    year: "120次/天",
  },
  {
    id: "ai-map",
    feature: "AI智能生成图谱",
    free: "16金币/次",
    week: "15次/天",
    month: "50次/天",
    year: "140次/天",
  },
  {
    id: "ai-use-case",
    feature: "AI生成用例文档",
    free: "16金币/次",
    week: "15次/天",
    month: "50次/天",
    year: "140次/天",
  },
  {
    id: "ai-mindmap",
    feature: "AI生成思维导图",
    free: "16金币/次",
    week: "12次/天",
    month: "40次/天",
    year: "120次/天",
  },
  {
    id: "ai-cover",
    feature: "AI生成海报卡片",
    free: "16金币/次",
    week: "12次/天",
    month: "40次/天",
    year: "120次/天",
  },
  {
    id: "ai-word",
    feature: "Word表格生成",
    free: "16金币/次",
    week: "15次/天",
    month: "40次/天",
    year: "120次/天",
  },
  {
    id: "doc-sql",
    category: "文档与转换",
    feature: "SQL转三线表",
    free: "1个节点1.5分钱",
    week: "15次/天",
    month: "45次/天",
    year: "120次/天",
  },
  {
    id: "doc-test",
    feature: "功能测试文档",
    free: "24金币/次",
    week: "15次/天",
    month: "45次/天",
    year: "120次/天",
  },
  {
    id: "doc-code",
    feature: "课设/毕设代码生成",
    free: "20金币/次",
    week: "9.2折",
    month: "8.6折",
    year: "7.5折",
  },
  {
    id: "vip-file",
    category: "专属权益",
    feature: "文件收集",
    free: "免费",
    week: "免费",
    month: "免费",
    year: "免费",
  },
  {
    id: "vip-service",
    feature: "7×24在线客服",
    free: "—",
    week: "—",
    month: "✓",
    year: "✓",
  },
  {
    id: "vip-priority",
    feature: "优先处理队列",
    free: "—",
    week: "基础",
    month: "✓",
    year: "✓",
  },
  {
    id: "vip-contact",
    feature: "专属客服联系方式",
    free: "—",
    week: "—",
    month: "✓",
    year: "✓",
  },
  {
    id: "vip-feature",
    feature: "新功能优先体验",
    free: "—",
    week: "—",
    month: "灰度",
    year: "✓",
  },
]

const memberFaqItems: MemberFaqItem[] = [
  {
    question: "金币与人民币如何换算？",
    answer:
      "采用基础换算 1元=120金币。不同充值档会提供额外赠送金币，实际到手单价通常低于基础换算。",
  },
  {
    question: "单个功能额度不足可以调配吗？",
    answer:
      "支持。会员可在会员中心发起调配申请，将同周期内剩余额度调配到目标功能，等级越高可调配次数越多。",
  },
  {
    question: "会员支持升级或续费吗？",
    answer:
      "支持续费叠加时长；升级走差额补充策略，到账后会立即刷新当前会员等级与每日额度。",
  },
  {
    question: "购买后没有生效怎么办？",
    answer:
      "可先刷新当前页面确认会员状态，再通过客服入口提交订单号。系统通常在数秒内完成权益同步。",
  },
]

export const memberPlanIds: MemberPlanId[] = ["free", "week", "month", "year"]

export const memberPreviewDocument: MemberCenterDocument = {
  heroNotice: {
    title: "功能次数灵活调配",
    description:
      "会员专享福利：某个功能额度用尽时，可按规则调配同周期剩余额度；等级越高，可调配上限与响应速度越高。",
  },
  centerTitle: "会员中心",
  centerDescription: "覆盖全站AI工具、文档生成与图表服务的统一会员方案",
  plans: memberPlanRows,
  purchaseNotice:
    "注意：会员为虚拟服务内容，购买后不支持退款。当前展示为平台自有定价策略（基础换算1元=120金币），如需升级、续费或额度调配请通过客服入口提交申请。",
  matrixTitle: "功能费用与次数详情",
  matrixDescription: "各会员等级的工具使用次数及费用一览",
  matrixHeaders: ["功能名称", "免费用户", "周会员", "月会员", "年会员"],
  matrixRows: memberMatrixRows,
  faqTitle: "会员常见问题",
  faqDescription: "以下问题覆盖购买、额度调配、升级续费等高频场景",
  faqs: memberFaqItems,
  activePlanId: "free",
  coinBalance: 5200,
}

export const memberDefaultPlanId: MemberPlanId = memberPreviewDocument.activePlanId
