import Link from "next/link";

import { CircleHelp } from "lucide-react";

import { PageIntro } from "@/components/system/page-intro";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { Button } from "@/components/ui/button";

const faqs = [
  {
    question: "生成的代码包含版权信息吗？可以商用吗？",
    answer: "免费版生成的代码会包含“Generated by Yunyan”的注释头，但您依然拥有代码的所有权。升级到专业版后，所有生成的代码将完全纯净，不包含任何厂商标识，完全支持商业闭源使用。",
  },
  {
    question: "如果我不懂 Java/Vue，能使用这个工具吗？",
    answer: "完全可以。云衍的设计初衷就是为了降低门槛。您只需要通过可视化的界面配置字段，或者直接上传 Excel 表格，我们就会为您生成可直接运行的完整项目。并且我们提供了“保姆级”的启动文档。",
  },
  {
    question: "支持哪些数据库？",
    answer: "目前完美支持 MySQL 5.7/8.0、PostgreSQL、SQLite。对于企业版用户，我们还支持 Oracle、SQL Server 以及国产达梦数据库的适配。",
  },
  {
    question: "生成的项目后续如何更新？",
    answer: "云衍生成的项目代码结构与手写无异，您可以像维护普通项目一样维护它。如果需要增加新表，您可以再次使用生成器生成新模块的代码，然后复制到项目中即可，不会覆盖您已有的业务逻辑（只要您遵循我们的扩展规范）。",
  },
];

export const FAQ = () => {
  return (
    <section className="py-16 lg:py-24">
      <div className="container max-w-5xl">
        <PageIntro
          icon={CircleHelp}
          title="常见问题解答"
          description="整理了高频问题与最佳实践，帮助您更快完成工程落地。"
          badge="Common Questions"
          className="mb-12"
          actions={(
            <Button asChild variant="outline" className="h-10 rounded-xl border-2 px-5 font-bold">
              <Link href="/contact">加入开发者交流群</Link>
            </Button>
          )}
        />

        <Accordion type="single" collapsible className="w-full space-y-4">
          {faqs.map((faq, i) => (
            <AccordionItem
              key={i}
              value={`item-${i}`}
              className="app-surface app-interactive rounded-2xl px-6 overflow-hidden hover:border-primary/20 data-[state=open]:border-primary/25 data-[state=open]:bg-background/80 data-[state=open]:shadow-lg"
            >
              <AccordionTrigger className="hover:no-underline py-6">
                <span className="text-left font-bold text-foreground text-base pr-4">
                  {faq.question}
                </span>
              </AccordionTrigger>
              <AccordionContent className="text-muted-foreground text-sm leading-relaxed pb-6">
                {faq.answer}
              </AccordionContent>
            </AccordionItem>
          ))}
        </Accordion>

        <div className="mt-12 text-center">
          <div className="inline-flex items-center gap-4 p-1 bg-background/50 backdrop-blur-xl rounded-full border border-primary/10 pl-5 pr-1 py-1">
            <span className="text-xs font-bold text-muted-foreground">还有其他疑问？</span>
            <Button size="sm" className="rounded-full h-8 px-4 text-xs font-bold bg-primary text-white hover:bg-primary/90">
              联系客服
            </Button>
          </div>
        </div>
      </div>
    </section>
  );
};
