import type {
  WalletDashboardDocument,
  WalletLedgerStatus,
  WalletLedgerType,
  WalletOrderStatus,
  WalletPaymentMethod,
} from "@/features/tools/wallet/types/wallet"

export const walletQuickRechargeAmounts = [10, 20, 50, 100, 200] as const

export const walletLedgerTypeLabelMap: Record<WalletLedgerType, string> = {
  recharge: "充值到账",
  consume: "功能消费",
  reward: "活动奖励",
  refund: "异常返还",
  adjustment: "人工调账",
}

export const walletLedgerStatusLabelMap: Record<WalletLedgerStatus, string> = {
  done: "完成",
  pending: "处理中",
  failed: "失败",
}

export const walletOrderStatusLabelMap: Record<WalletOrderStatus, string> = {
  paid: "支付成功",
  pending: "待支付",
  failed: "支付失败",
}

export const walletPaymentMethodLabelMap: Record<WalletPaymentMethod, string> = {
  alipay: "支付宝",
  wechat: "微信支付",
}

export const walletFaqItems = [
  {
    question: "金币到账需要多久？",
    answer:
      "正常支付成功后通常 5-30 秒到账。如超过 3 分钟未到账，可在钱包页点击刷新并提交订单号给客服。",
  },
  {
    question: "金币可以提现吗？",
    answer:
      "金币为平台虚拟权益，仅用于工具调用、会员兑换和活动权益，不支持提现或转账到外部账户。",
  },
  {
    question: "为什么会出现负数余额？",
    answer:
      "为保证高并发操作体验，系统会先记账再校验。若出现负数，请优先充值或联系支持进行对账处理。",
  },
  {
    question: "钱包和会员如何联动？",
    answer:
      "钱包充值后可在会员中心直接订阅。订阅扣费与钱包余额保持实时同步，后端接入后将以账户中心为准。",
  },
] as const

export const walletPreviewDocument: WalletDashboardDocument = {
  userName: "用户oztqsy",
  joinedAt: "2026-01-25",
  usedDays: 32,
  inviteCode: "hhGGqy",
  promoBar:
    "限时活动：充值满20送240金币，满100送1600金币，满200送4200金币。钱包充值后可直接用于会员订阅与工具消费。",
  balance: 5200,
  ratioBase: 120,
  bonusRules: [
    {
      thresholdYuan: 20,
      bonusCoins: 240,
      label: "入门赠送",
    },
    {
      thresholdYuan: 100,
      bonusCoins: 1600,
      label: "高频奖励",
    },
    {
      thresholdYuan: 200,
      bonusCoins: 4200,
      label: "项目冲刺包",
    },
  ],
  paymentMethods: [
    {
      id: "alipay",
      label: "支付宝支付",
      recommended: true,
    },
    {
      id: "wechat",
      label: "微信支付",
    },
  ],
  quickActions: [
    {
      id: "member",
      title: "会员说明",
      description: "查看钱包与会员扣费联动规则",
    },
    {
      id: "activity",
      title: "活动中心",
      description: "查看任务奖励与限时福利说明",
    },
    {
      id: "orders",
      title: "订单中心",
      description: "查看支付状态与到账记录",
    },
    {
      id: "support",
      title: "人工支持",
      description: "异常扣费处理与人工联系入口",
    },
  ],
  rewardTasks: [
    {
      id: "reward-signin",
      title: "连续签到 5 天",
      description: "完成后可领取金币奖励",
      rewardCoins: 80,
      progressCurrent: 5,
      progressTarget: 5,
      status: "claimable",
      actionLabel: "领取",
    },
    {
      id: "reward-share",
      title: "分享工具页面",
      description: "社交平台发布体验内容",
      rewardCoins: 200,
      progressCurrent: 1,
      progressTarget: 1,
      status: "claimable",
      actionLabel: "领取",
    },
    {
      id: "reward-feedback",
      title: "提交产品反馈",
      description: "有效建议可提升工具体验",
      rewardCoins: 120,
      progressCurrent: 1,
      progressTarget: 1,
      status: "claimed",
      actionLabel: "已领取",
    },
    {
      id: "reward-guide",
      title: "完成新手引导",
      description: "了解钱包和会员联动流程",
      rewardCoins: 60,
      progressCurrent: 0,
      progressTarget: 1,
      status: "todo",
      actionLabel: "去完成",
    },
  ],
  ledger: [
    {
      id: "WL-1009",
      type: "consume",
      description: "开通月会员（30天）",
      deltaCoins: -3980,
      balanceAfter: 5200,
      createdAt: "2026-02-26 10:20:12",
      source: "会员中心",
      status: "done",
    },
    {
      id: "WL-1008",
      type: "recharge",
      description: "充值到账 ¥100（含赠送）",
      deltaCoins: 13600,
      balanceAfter: 9180,
      createdAt: "2026-02-26 10:18:03",
      source: "支付宝",
      status: "done",
    },
    {
      id: "WL-1007",
      type: "reward",
      description: "活动奖励：分享任务",
      deltaCoins: 200,
      balanceAfter: 5180,
      createdAt: "2026-02-25 16:22:44",
      source: "活动中心",
      status: "done",
    },
    {
      id: "WL-1006",
      type: "consume",
      description: "AIGC检测（3次）",
      deltaCoins: -360,
      balanceAfter: 4980,
      createdAt: "2026-02-25 12:15:08",
      source: "AIGC检测",
      status: "done",
    },
    {
      id: "WL-1005",
      type: "consume",
      description: "论文降重（2次）",
      deltaCoins: -320,
      balanceAfter: 5340,
      createdAt: "2026-02-25 11:48:17",
      source: "论文降重",
      status: "done",
    },
    {
      id: "WL-1004",
      type: "recharge",
      description: "充值到账 ¥20（含赠送）",
      deltaCoins: 2640,
      balanceAfter: 5660,
      createdAt: "2026-02-24 20:09:55",
      source: "支付宝",
      status: "done",
    },
    {
      id: "WL-1003",
      type: "refund",
      description: "异常任务自动返还",
      deltaCoins: 180,
      balanceAfter: 3020,
      createdAt: "2026-02-24 17:01:21",
      source: "系统",
      status: "done",
    },
    {
      id: "WL-1002",
      type: "consume",
      description: "SQL转三线表（5次）",
      deltaCoins: -240,
      balanceAfter: 2840,
      createdAt: "2026-02-24 16:33:01",
      source: "SQL转三线表",
      status: "done",
    },
    {
      id: "WL-1001",
      type: "reward",
      description: "签到奖励",
      deltaCoins: 10,
      balanceAfter: 3080,
      createdAt: "2026-02-24 08:03:25",
      source: "签到",
      status: "done",
    },
  ],
  orders: [
    {
      id: "WO-8842",
      orderNo: "PAY20260226101803",
      amountYuan: 100,
      coins: 12000,
      bonusCoins: 1600,
      totalCoins: 13600,
      method: "alipay",
      status: "paid",
      createdAt: "2026-02-26 10:18:03",
    },
    {
      id: "WO-8820",
      orderNo: "PAY20260224200955",
      amountYuan: 20,
      coins: 2400,
      bonusCoins: 240,
      totalCoins: 2640,
      method: "alipay",
      status: "paid",
      createdAt: "2026-02-24 20:09:55",
    },
    {
      id: "WO-8819",
      orderNo: "PAY20260224185810",
      amountYuan: 10,
      coins: 1200,
      bonusCoins: 0,
      totalCoins: 1200,
      method: "wechat",
      status: "failed",
      createdAt: "2026-02-24 18:58:10",
    },
  ],
  notices: [
    "金币余额与会员订阅共享同一账户，开通会员后会实时扣减余额。",
    "账单导出支持 CSV，可用于财务对账或教学报销。",
    "后端接口接入后将以支付回调状态为准，本地仅模拟流程。",
  ],
  products: [
    {
      id: "product-sql",
      name: "SQL转三线表",
      category: "论文工具",
      summary: "将 SQL 结构化内容转换为论文可用表格格式。",
      status: "enabled",
      consumeHint: "5 金币/次",
      dailyLimitHint: "无限次",
    },
    {
      id: "product-aigc-detect",
      name: "AIGC检测",
      category: "检测工具",
      summary: "检测文本 AI 生成概率并输出段落分析建议。",
      status: "enabled",
      consumeHint: "12 金币/次",
      dailyLimitHint: "50 次/日",
    },
    {
      id: "product-code-runner",
      name: "在线代码运行",
      category: "开发工具",
      summary: "支持多语言在线编译运行与输出结果查看。",
      status: "trial",
      consumeHint: "首月免费，后续按量",
      dailyLimitHint: "20 次/日",
    },
    {
      id: "product-paper-lower",
      name: "论文降重Pro",
      category: "论文工具",
      summary: "针对学术表达进行风险段落重写与可读性优化。",
      status: "locked",
      consumeHint: "会员专享",
      dailyLimitHint: "开通后解锁",
    },
  ],
  announcements: [
    {
      id: "notice-wallet-20260226",
      title: "充值回调链路升级通知",
      level: "success",
      content: "已完成支付回调链路优化，预计到账延迟降低至 5-30 秒。",
      publishedAt: "2026-02-26 09:30:00",
      read: false,
    },
    {
      id: "notice-wallet-20260224",
      title: "账单导出结构调整",
      level: "info",
      content: "新增来源字段与订单号映射，便于财务对账与复核。",
      publishedAt: "2026-02-24 18:10:00",
      read: true,
    },
    {
      id: "notice-wallet-20260222",
      title: "异常扣费复核入口上线",
      level: "warning",
      content: "若出现疑似误扣，可在“联系我们”提交工单并附上订单号。",
      publishedAt: "2026-02-22 11:05:00",
      read: false,
    },
  ],
  messages: [
    {
      id: "msg-20260226-1",
      title: "充值到账提醒",
      category: "order",
      summary: "你的订单 PAY20260226101803 已支付成功，到账 13600 金币。",
      createdAt: "2026-02-26 10:18:12",
      read: false,
    },
    {
      id: "msg-20260225-1",
      title: "奖励可领取提醒",
      category: "reward",
      summary: "任务“分享工具页面”已完成，可领取 200 金币奖励。",
      createdAt: "2026-02-25 16:20:09",
      read: false,
    },
    {
      id: "msg-20260224-1",
      title: "安全登录提醒",
      category: "security",
      summary: "你的账号于 2026-02-24 21:08 在新设备登录，请确认是否本人操作。",
      createdAt: "2026-02-24 21:08:16",
      read: true,
    },
  ],
  contactChannels: [
    {
      id: "contact-ticket",
      name: "在线工单",
      value: "钱包中心 > 联系我们 > 提交工单",
      availableAt: "7x24",
      responseSla: "2小时内首响",
    },
    {
      id: "contact-email",
      name: "邮箱支持",
      value: "support@yunyantools.com",
      availableAt: "工作日 09:00-18:00",
      responseSla: "24小时内回复",
    },
    {
      id: "contact-service",
      name: "人工值班",
      value: "企业微信：YUNYAN-SERVICE",
      availableAt: "工作日 10:00-19:00",
      responseSla: "30分钟内响应",
    },
  ],
  supportTickets: [
    {
      id: "ticket-20260226-1",
      category: "充值问题",
      subject: "订单到账延迟",
      detail: "订单 PAY20260226101803 到账超过 2 分钟，需确认流水状态。",
      status: "resolved",
      createdAt: "2026-02-26 10:21:00",
    },
    {
      id: "ticket-20260224-1",
      category: "扣费核对",
      subject: "疑似重复扣费",
      detail: "AIGC检测任务编号 AG-2208 疑似重复扣费，请协助核查。",
      status: "processing",
      createdAt: "2026-02-24 12:48:00",
    },
  ],
  profile: {
    nickname: "oztqsy",
    email: "oztqsy@example.com",
    phone: "138****9201",
    company: "云研工具实验室",
    security2FAEnabled: true,
  },
}
